import { Signal, TradingSignal, SignalQuality } from '../types';
import { getQualityScore } from '../utils/helpers';
import { SIGNAL_THRESHOLDS } from '../utils/constants';

// ============================================================
// SIGNAL SERVICE
// ============================================================

export class SignalService {
  /**
   * Map raw API signals to enriched TradingSignal objects
   */
  mapSignalData(apiSignals: Signal[]): TradingSignal[] {
    if (!apiSignals || apiSignals.length === 0) return [];

    return apiSignals.map((s, index) => ({
      id: `sig-${Date.now()}-${index}-${Math.random().toString(36).substr(2, 6)}`,
      pair: s.pair || '',
      signal: s.signal || 'HOLD',
      confidence: s.confidence || 0,
      price: s.price || 0,
      strength: s.strength || 'NEUTRAL',
      timestamp: s.timestamp || new Date().toISOString(),
      entry: s.price || 0,
      stopLoss: s.price ? Math.round(s.price * 0.95 * 100) / 100 : 0,
      tp1: s.price ? Math.round(s.price * 1.05 * 100) / 100 : 0,
      tp2: s.price ? Math.round(s.price * 1.10 * 100) / 100 : 0,
      quality: this.getSignalQuality(s.confidence || 0),
      riskReward: this.calculateRiskReward(s.price || 0, 0.95, 1.05),
      mtfAlignment: this.generateMTFAlignment(s),
      reasons: this.generateReasons(s),
      riskLevel: this.getRiskLevel(s.confidence || 0, s.strength || 'NEUTRAL'),
      trend: this.getTrend(s.signal || 'HOLD'),
      timeframe: '1h',
    }));
  }

  /**
   * Enrich signals with additional data
   */
  enrichSignals(signals: TradingSignal[]): TradingSignal[] {
    return signals.map(s => ({
      ...s,
      quality: this.getSignalQuality(s.confidence),
      riskReward: this.calculateRiskReward(s.entry, 0.95, 1.05),
      riskLevel: this.getRiskLevel(s.confidence, s.strength),
    }));
  }

  /**
   * Get signal quality based on confidence
   */
  private getSignalQuality(confidence: number): SignalQuality {
    if (confidence >= SIGNAL_THRESHOLDS.EXCELLENT_CONFIDENCE) return 'EXCELLENT';
    if (confidence >= SIGNAL_THRESHOLDS.GOOD_CONFIDENCE) return 'GOOD';
    return 'NEUTRAL';
  }

  /**
   * Calculate risk/reward ratio
   */
  private calculateRiskReward(entry: number, stopLossPercent: number, takeProfitPercent: number): number {
    if (!entry || entry <= 0) return 0;
    const risk = entry * (1 - stopLossPercent);
    const reward = entry * (takeProfitPercent - 1);
    return risk > 0 ? reward / risk : 0;
  }

  /**
   * Generate MTF (Multi-Timeframe) alignment
   */
  private generateMTFAlignment(signal: Signal): TradingSignal['mtfAlignment'] {
    const base = signal.signal === 'BUY' ? 'BULLISH' : 
                 signal.signal === 'SELL' ? 'BEARISH' : 'NEUTRAL';
    const strong = signal.strength === 'STRONG';
    
    return {
      '5m': strong ? base : 'NEUTRAL',
      '15m': signal.signal === 'BUY' ? 'BULLISH' : 
              signal.signal === 'SELL' ? 'BEARISH' : 'NEUTRAL',
      '1h': signal.signal === 'BUY' ? 'BULLISH' : 
            signal.signal === 'SELL' ? 'BEARISH' : 'NEUTRAL',
      '4h': 'NEUTRAL',
      '1d': 'NEUTRAL',
    };
  }

  /**
   * Generate reasons for signal
   */
  private generateReasons(signal: Signal): string[] {
    const reasons = [
      `Signal generated by cognitive engine for ${signal.pair}`,
      `Confidence: ${signal.confidence}%`,
      `Strength: ${signal.strength || 'NEUTRAL'}`,
    ];
    
    if (signal.confidence > 80) {
      reasons.push('High confidence signal - strong conviction');
    } else if (signal.confidence > 60) {
      reasons.push('Moderate confidence - consider risk management');
    }
    
    return reasons;
  }

  /**
   * Get risk level based on confidence and strength
   */
  private getRiskLevel(confidence: number, strength: string): 'LOW' | 'MEDIUM' | 'HIGH' {
    if (confidence > 80 && strength === 'STRONG') return 'LOW';
    if (confidence > 60) return 'MEDIUM';
    return 'HIGH';
  }

  /**
   * Get trend direction from signal
   */
  private getTrend(signal: string): string {
    if (signal === 'BUY') return 'BULLISH';
    if (signal === 'SELL') return 'BEARISH';
    return 'NEUTRAL';
  }

  /**
   * Filter signals by quality
   */
  filterByQuality(signals: TradingSignal[], quality: SignalQuality): TradingSignal[] {
    return signals.filter(s => s.quality === quality);
  }

  /**
   * Filter signals by pair
   */
  filterByPair(signals: TradingSignal[], pair: string): TradingSignal[] {
    return signals.filter(s => s.pair === pair);
  }

  /**
   * Get latest signal for each pair
   */
  getLatestSignals(signals: TradingSignal[]): TradingSignal[] {
    const map = new Map<string, TradingSignal>();
    for (const signal of signals) {
      if (!map.has(signal.pair) || new Date(signal.timestamp) > new Date(map.get(signal.pair)!.timestamp)) {
        map.set(signal.pair, signal);
      }
    }
    return Array.from(map.values());
  }

  /**
   * Sort signals by confidence (descending)
   */
  sortByConfidence(signals: TradingSignal[]): TradingSignal[] {
    return [...signals].sort((a, b) => b.confidence - a.confidence);
  }

  /**
   * Sort signals by timestamp (newest first)
   */
  sortByTimestamp(signals: TradingSignal[]): TradingSignal[] {
    return [...signals].sort((a, b) => 
      new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );
  }
}

export const signalService = new SignalService();
export default signalService;
